# DEPRICATED, NOT USED IN CURRENT CODE VERSION
# ALL PARAMETERS MUST BE SET MANUALLY USING GUI!!!!!!!!!!!!!!!!!!!!
seq_threshhold_depth: 10
path_to_input_file: "C:/Users/Arekusei/Documents/snp_program/SNP_analyser/input.xlsx"
aggregation_method: 'mean' # also 'min' and 'max' possible